name: "Darkin's Photography and Poetry"
favicon: null
layout_spectrum: 0.45074
typography_spectrum: 0.5062
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
