name: "Darkin's Art"
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: 'Photography, Poetry, and other tidbits'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040809'
    - '#3170a5'
    - '#c4c2c3'
    - '#825737'
    - '#d09f6e'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
